# Generated by Django 5.1.6 on 2025-04-17 10:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmobeauty', '0005_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zipcode', models.CharField(max_length=30)),
                ('amount', models.CharField(max_length=255)),
                ('payment_mode', models.CharField(choices=[('Online', 'Online'), ('COD', 'COD')], max_length=255)),
                ('billing_date', models.DateField(auto_now_add=True)),
                ('orderid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cosmobeauty.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
